Compare,Pivoting & Melting

In [2]:
import pandas as pd

In [6]:
shop_Oct8={
    "fruits":['mango','apple','banana','papaya'],
    'Price':[100,150,60,30],
    "quint":[10,8,12,15]
    }
stock_Oct8=pd.DataFrame(shop_Oct8)
shop_Oct9={
    "fruits":['mango','apple','banana','papaya'],
    'Price':[120,200,60,35],
    "quint":[15,6,24,13]
    }
stock_Oct9=pd.DataFrame(shop_Oct9)
#---------------Compare---------------#
stock_Oct8.compare(stock_Oct9)
stock_Oct8.compare(stock_Oct9,align_axis=0)
stock_Oct8.compare(stock_Oct9,align_axis=0,keep_equal=True)
stock_Oct8.compare(stock_Oct9,align_axis=0,keep_equal=True,keep_shape=True)

         fruits  Price  quint
0 self    mango    100     10
  other   mango    120     15
1 self    apple    150      8
  other   apple    200      6
2 self   banana     60     12
  other  banana     60     24
3 self   papaya     30     15
  other  papaya     35     13

In [ ]:
monthly_sales={
    "Products":["laptop","mobile","laptop","mobile","laptop","laptop"],
    "Month":['Jan','Jan','Feb','Feb','Mar','Mar'],
    "Price":[65000,25000,78500,17500,75000,45000]
}
sales=pd.DataFrame(monthly_sales)
sales

#--------Pivoting--------#
sales.pivot(
    columns="Month",
    index="Products",
    values="Price"
    )

Month         Apr      Feb      Jan      Mar
Products
laptop    45000.0  78500.0  65000.0  75000.0
mobile        NaN  17500.0  25000.0      NaN

In [20]:
monthly_sales={
    "Products":["laptop","mobile","laptop","mobile","laptop","laptop"],
    "Month":['Jan','Jan','Feb','Feb','Mar','Mar'],
    "Price":[65000,25000,78500,17500,75000,45000]
}
sales=pd.DataFrame(monthly_sales)
sales

#--------Pivoting--------#
sales.pivot_table(
    columns="Month",
    index="Products",
    values="Price",
    aggfunc='sum'
    )

Month         Feb      Jan       Mar
Products
laptop    78500.0  65000.0  120000.0
mobile    17500.0  25000.0       NaN

In [ ]:
shop_sales={
    "products":['laptop','mobile','mouse'],
    "january":[10000,50000,1000],
    "feb":[5500,9999,7776],
    "marh/":[12221,22555,8855]
}
sales=pd.DataFrame(shop_sales)
# melting
sales.melt(id_vars='products', var_name='month', value_name='price')

  products    month  price
0   laptop  january  10000
1   mobile  january  50000
2    mouse  january   1000
3   laptop      feb   5500
4   mobile      feb   9999
5    mouse      feb   7776
6   laptop     marh  12221
7   mobile     marh  22555
8    mouse     marh   8855