Creation of Dataframes,Exploring Data

In [2]:
import pandas as pd

Data Frames

In [14]:
student_data={
    'name':['vineeth','swasthik','sunil','suman'],
    'age':[20,18,21,17],
    'marks':[91,87,86,67]
}
df=pd.DataFrame(student_data)

In [ ]:
#shape
df.shape
#coloumns
df.columns
#Size
df.size
#Rename
df.rename(columns={'marks':'total_marks'},inplace=True)
print(df)

       name  age  total_marks
0   vineeth   20           91
1  swasthik   18           87
2     sunil   21           86
3     suman   17           67

In [ ]:
df.to_csv("student_data.csv")
df.to_csv("student_data.csv",index=False)

Import CSV Files

In [26]:
#Same Folder
samedf=pd.read_csv("companydemo.csv")
samedf
#from df folder
diff_df=pd.read_csv("C:/Users/Sushant sapaliga/Pandas/Dataset_Pandas/company.csv")
diff_df

    EEID      Name gender   salary
0  EMP01    ayushi      F      NaN
1  EMP02     rohit      M  25000.0
2  EMP03  pranjali    NaN  27000.0
3  EMP01    ayushi      F  20000.0
4  EMP05       NaN      M  25000.0
5  EMP06     rohit      M      NaN
6  EMP02     rohit      M  25000.0

Series in pandas
Is as one dimansional labeled array capable of holding data of any type (integer,string,float,python objects,etc.)

DataFrames in Pandas:

 is two-dimensional size-mutable,potentially heterogenous tabular data structure with labeled axis(rows and columns)

Pandas DataFrame consists of three principle components,the data,rows,and columns

In [3]:
#cms:-> pip install openpyxl
excel_df=pd.read_excel("C:/Users/Sushant sapaliga/Pandas/Dataset_Pandas/expense.xlsx")
excel_df

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04        Food              Zomato     257          NaN
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000          UPI
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50          NaN
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          NaN
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000          NaN
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

Exploring Data

In [9]:

df=pd.read_csv("C:/Users/Sushant sapaliga/Pandas/Dataset_Pandas/employee.csv")
df

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,1,Male,03-02-1952,15,IT,57000,27000,8.17,NaN,No
1,2,Male,23-05-1958,16,IT,40200,18750,8.17,3.00,No
2,3,Female,26-07-1929,12,Finance,21450,12000,8.17,31.75,No
3,4,Female,15-04-1947,18,IT,21900,13200,8.17,15.83,No
4,5,Male,09-02-1955,15,Finance,45000,21000,8.17,11.50,No
...,...,...,...,...,...,...,...,...,...,...
469,470,Male,22-01-1964,12,IT,26250,15750,5.33,5.75,Yes
470,471,Male,03-08-1966,15,Engineering,26400,15750,5.33,2.67,Yes
471,472,Male,21-02-1966,15,Sales,39150,15750,5.25,3.83,No
472,473,Female,25-11-1937,12,Marketing,21450,12750,5.25,11.58,No
473,474,Female,05-11-1968,12,IT,29400,14250,5.25,0.75,No

In [ ]:
#From top 10 rows
df.head(10)
#From Bottom
df.tail(10)
#Count rows and column
df.shape
#Size
df.size
#Describe
df.describe()
#Info
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 474 entries, 0 to 473
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   id                   474 non-null    int64
 1   gender               474 non-null    str
 2   dateofbirth          473 non-null    str
 3   education            474 non-null    int64
 4   department           474 non-null    str
 5   salary               474 non-null    int64
 6   starting_salary      474 non-null    int64
 7   job_time             474 non-null    float64
 8   previous_experience  449 non-null    float64
 9   minority             471 non-null    str
dtypes: float64(2), int64(4), str(4)
memory usage: 37.2 KB

In [13]:
df.isnull()

,id,gender,dateofbirth,education,department,salary,starting_salary,job_time,previous_experience,minority
0,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
469,False,False,False,False,False,False,False,False,False,False
470,False,False,False,False,False,False,False,False,False,False
471,False,False,False,False,False,False,False,False,False,False
472,False,False,False,False,False,False,False,False,False,False
473,False,False,False,False,False,False,False,False,False,False

In [14]:
df.isnull().sum()

id                      0
gender                  0
dateofbirth             1
education               0
department              0
salary                  0
starting_salary         0
job_time                0
previous_experience    25
minority                3
dtype: int64