In [2]:
import pandas as pd

##GroupBy

In [ ]:
exp=pd.read_excel("Dataset_Pandas/expense.xlsx")
exp

         Date    Category       Sub-Category   Amount Payment Mode
0  2023-01-01     Grocery             Grocery      30         Cash
1  2023-01-02        Food          Restaurant     890          UPI
2  2023-01-04        Food              Zomato     257          NaN
3  2023-01-06  Essentials               Diary     120          UPI
4  2023-01-06  Essentials             Perfume    1500         Cash
5  2023-01-09     Grocery  Fruits and Veggies     456         Cash
6  2023-01-10       Bills          House Rent   16000          UPI
7  2023-01-10     Grocery      Tomato KetchUp      70          UPI
8  2023-01-12        Food                Chai      15          UPI
9  2023-01-15  Essentials      Salt and Sugar      50          NaN
10 2023-01-17     Grocery           Chocolate     100          UPI
11 2023-01-17        Food          Restaurant     780         Card
12 2023-01-18  Essentials            Food Oil     120          NaN
13 2023-01-18        Food              Zomato     230          UPI
14 2023-01-19     Grocery                Milk      26          UPI
15 2023-01-20  Essentials             Shampoo     780          UPI
16 2023-01-20  Essentials           Lunch Box     890         Cash
17 2023-01-21     Clothes               Dress    1000          NaN
18 2023-01-22     Clothes               Dress    1890          UPI
19 2023-01-23     Grocery      Bread and Milk      56         Cash
20 2023-01-24        Food  Fruits and Veggies     530         Cash
21 2023-01-26        Food                Chai      10          UPI
22 2023-01-26     Grocery               Maggi     140          UPI
23 2023-01-27        Food              Zomato     300          UPI
24 2023-01-27        Food                Chai      10          UPI
25 2023-01-28  Essentials           Bedsheets    1025         Cash
26 2023-01-29       Bills             Mobile     1650          UPI
27 2023-01-29     Grocery                Daal     150         Cash
28 2023-01-30       Bills            Cylinder    1074          UPI

In [ ]:
#Find the total expense for each category
exp.groupby('Category')['Amount'].sum() #M1
exp.groupby('Category')['Amount'].agg(['sum']) #M2
#Give a complete expense summary for each category.
exp.groupby('Category')['Amount'].agg(['sum','count','mean','max','min']) #M2
#3.  How much money was paid by each payment mode
exp.groupby('Payment Mode')['Amount'].agg(['sum']) #M2
#3.  How many transaction made using each payment mode
exp.groupby('Payment Mode')['Amount'].agg(['sum','count']) #M2

                sum  count
Payment Mode
Card            780      1
Cash           4637      8
UPI           23305     16

In [ ]:
#5.For  each payment mode,calculate the total spent across categories
exp.groupby(['Payment Mode','Category'])['Amount'].agg(['sum'])
#5.For  each payment mode,calculate the total spent across Payment Mode
exp.groupby(['Category','Payment Mode'])['Amount'].agg(['sum'])

#Which categories have the  highest total expenses?
exp.groupby('Category')['Amount'].sum().sort_values

                           sum
Category   Payment Mode
Bills      UPI           18724
Clothes    UPI            1890
Essentials Cash           3415
           UPI             900
Food       Card            780
           Cash            530
           UPI            1455
Grocery    Cash            692
           UPI             336

#MergeOrJoin

In [12]:
customer=pd.read_csv('Dataset_Pandas/customer.csv')
customer
payment=pd.read_csv('Dataset_Pandas/payment.csv')

In [3]:
#-------------Join------------
#Inner join
pd.merge(left=customer,right=payment,on="customerid",how="inner")
#Left join
pd.merge(left=customer,right=payment,on="customerid",how="left")
#Right
pd.merge(left=customer,right=payment,on="customerid",how="right")

NameError: name 'customer' is not defined